apiVersion: v1
kind: Pod
metadata:
  name: resource-limits-demo
spec:
  containers:
  - name: app-container
    image: myapp:latest
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
