apiVersion: v1
kind: Pod
metadata:
  name: resource-requests-demo
spec:
  containers:
  - name: app-container
    image: myapp:latest
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
