name: Accediendo a var and secret

on:
  workflow_dispatch

jobs:
  show-repo-var-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar valor del secret
        run: echo "My var ${{ vars.MY_VAR }} and my secret ${{ secrets.MY_PASSWORD }}"
